- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    back: ClothingBackpackSatchelCentcomFilled
    mask: ClothingMaskGasCentcom
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCommand
    pocket1: RubberStampCentcom
    pocket2: BoxFolderBlue
