- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  requirements:
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 18000
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  canBeAntag: false
  antagAdvantage: 10
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAtmos
    back: ClothingBackpackAtmosphericsFilled
    shoes: ClothingShoesColorWhite
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  innerclothingskirt: ClothingUniformJumpskirtAtmos
  satchel: ClothingBackpackSatchelAtmosphericsFilled
  duffelbag: ClothingBackpackDuffelAtmosphericsFilled
