- type: latheRecipe
  id: Handcuffs
  result: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  result: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  id: Stunbaton
  result: Stunbaton
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: Truncheon
  result: Truncheon
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  completetime: 30
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  id: WeaponCutter
  result: WeaponCutter
  completetime: 10
  materials:
    Steel: 1100
    Glass: 200
    Gold: 300
    Plasma: 800
  
- type: latheRecipe
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  completetime: 20
  materials:
    Steel: 1000
    Glass: 500
    Gold: 150
    Uranium: 600

- type: latheRecipe
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  completetime: 5
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 100

- type: latheRecipe
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  completetime: 5
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 100

- type: latheRecipe
  id: WeaponTaser
  result: WeaponTaser
  completetime: 5
  materials:
    Steel: 700
    Plastic: 300
    Gold: 250
    Silver: 500

- type: latheRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesGlassesSecurity
  result: ClothingEyesGlassesSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: RiotShield
  result: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: Flash
  result: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  id: ShellShotgunBeanbag
  result: ShellShotgunBeanbag
  completetime: 2
  materials:
    Plastic: 15
    Steel: 10

- type: latheRecipe
  id: CartridgePistolRubber
  result: CartridgePistolRubber
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeMagnumRubber
  result: CartridgeMagnumRubber
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeRifle
  result: CartridgeRifle
  completetime: 2
  materials:
    Steel: 15

- type: latheRecipe
  id: CartridgeLightRifleRubber
  result: CartridgeLightRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgeRifleRubber
  result: CartridgeRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgePistol
  result: CartridgePistol
  completetime: 2
  materials:
    Steel: 10

- type: latheRecipe
  id: CartridgePistolUranium
  result: CartridgePistolUranium
  completetime: 10
  materials:
    Uranium: 1
    Steel: 10

- type: latheRecipe
  id: ShellShotgun
  result: ShellShotgun
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeMagnum
  result: CartridgeMagnum
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeLightRifle
  result: CartridgeLightRifle
  completetime: 2
  materials:
    Steel: 30

- type: latheRecipe
  id: ShellShotgunFlare
  result: ShellShotgunFlare
  completetime: 2
  materials:
    Plastic: 20
    Steel: 5

- type: latheRecipe
  id: ShellTranquilizer
  result: ShellTranquilizer
  completetime: 4
  materials:
    Plastic: 15
    Steel: 10
    Glass: 5

- type: latheRecipe
  id: CartridgeAnomalousParticleDelta
  result: CartridgeAnomalousParticleDelta
  completetime: 2
  materials:
    Plastic: 25

- type: latheRecipe
  id: CartridgeAnomalousParticleEpsilon
  result: CartridgeAnomalousParticleEpsilon
  completetime: 2
  materials:
    Plastic: 25

- type: latheRecipe
  id: CartridgeAnomalousParticleZeta
  result: CartridgeAnomalousParticleZeta
  completetime: 2
  materials:
    Plastic: 25

- type: latheRecipe
  id: TargetHuman
  result: TargetHuman
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: TargetClown
  result: TargetClown
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: TargetSyndicate
  result: TargetSyndicate
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

# Magazines for SecurityTechFab and WeaponsTechFab
# Resource logic. [Number of rounds in magazine]*[Cartridge material] + 100 steel
# Complete time logic. [Number of rounds in magazine]*[Cartridge complete time] + 5
- type: latheRecipe
  id: MagazinePistolRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pistol_mag.rsi
    state: rubber
  result: MagazinePistolRubber
  completetime: 10
  materials:
    Plastic: 50
    Steel: 150

- type: latheRecipe
  id: SpeedLoaderMagnumRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/SpeedLoaders/Magnum/magnum_speed_loader.rsi
    state: rubber-6
  result: SpeedLoaderMagnumRubber
  completetime: 10
  materials:
    Plastic: 50
    Steel: 150

- type: latheRecipe
  id: MagazineLightRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_mag.rsi
    state: rubber
  result: MagazineLightRifleRubber
  completetime: 20
  materials:
    Plastic: 300
    Steel: 250

- type: latheRecipe
  id: MagazineRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Rifle/rifle_mag.rsi
    state: rubber
  result: MagazineRifleRubber
  completetime: 20
  materials:
    Plastic: 250
    Steel: 225

- type: latheRecipe
  id: MagazineMagnumSubMachineGunRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Magnum/magnum_smg_mag.rsi
    state: rubber
  result: MagazineMagnumSubMachineGunRubber
  completetime: 20
  materials:
    Plastic: 250
    Steel: 250

- type: latheRecipe
  id: MagazinePistol
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pistol_mag.rsi
    state: red
  result: MagazinePistol
  completetime: 10
  materials:
    Steel: 200

- type: latheRecipe
  id: SpeedLoaderMagnum
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/SpeedLoaders/Magnum/magnum_speed_loader.rsi
    state: base-6
  result: SpeedLoaderMagnum
  completetime: 10
  materials:
    Steel: 200

- type: latheRecipe
  id: MagazineLightRifle
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_mag.rsi
    state: red
  result: MagazineLightRifle
  completetime: 20
  materials:
    Steel: 1000

- type: latheRecipe
  id: MagazineRifle
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Rifle/rifle_mag.rsi
    state: red
  result: MagazineRifle
  completetime: 20
  materials:
    Plastic: 250
    Steel: 225

- type: latheRecipe
  id: MagazineMagnumSubMachineGun
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Magnum/magnum_smg_mag.rsi
    state: red
  result: MagazineMagnumSubMachineGun
  completetime: 20
  materials:
    Steel: 350

- type: latheRecipe
  id: MagazinePistolSubMachineGunTopMounted
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Pistol/smg_mag_top_mounted.rsi
    state: mag-unshaded-5
  result: MagazinePistolSubMachineGunTopMounted
  completetime: 20
  materials:
    Plastic: 100
    Steel: 250

# Magazines for SecurityTechFab
# Weapons kinetic
- type: latheRecipe
  id: WeaponRevolverInspector
  icon:
    sprite: Objects/Weapons/Guns/Revolvers/inspector.rsi
    state: icon
  result: WeaponRevolverInspector
  completetime: 15
  materials:
    Steel: 600

- type: latheRecipe
  id: WeaponSubMachineGunWt550
  icon:
    sprite: Objects/Weapons/Guns/SMGs/wt550.rsi
    state: base
  result: WeaponSubMachineGunWt550
  completetime: 30
  materials:
    Plastic: 250
    Steel: 1200

- type: latheRecipe
  id: WeaponRifleLecter
  icon:
    sprite: Objects/Weapons/Guns/Rifles/lecter.rsi
    state: base
  result: WeaponRifleLecter
  completetime: 30
  materials:
    Plastic: 250
    Steel: 1600

- type: latheRecipe
  id: WeaponShotgunDoubleBarreled
  icon:
    sprite: Objects/Weapons/Guns/Shotguns/db_shotgun.rsi
    state: icon
  result: WeaponShotgunDoubleBarreled
  completetime: 20
  materials:
    Wood: 600
    Steel: 600

- type: latheRecipe
  id: WeaponPistolMk58
  icon:
    sprite: Objects/Weapons/Guns/Pistols/mk58.rsi
    state: base
  result: WeaponPistolMk58
  completetime: 15
  materials:
    Steel: 600

- type: latheRecipe
  id: WeaponSubMachineGunVector
  icon:
    sprite: Objects/Weapons/Guns/SMGs/vector.rsi
    state: base
  result: WeaponSubMachineGunVector
  completetime: 30
  materials:
    Plastic: 400
    Steel: 1200

# Weapons energy
- type: latheRecipe
  id: WeaponDisabler
  icon:
    sprite: Objects/Weapons/Guns/Battery/disabler.rsi
    state: base
  result: WeaponDisabler
  completetime: 15
  materials:
    Glass: 350
    Steel: 350

- type: latheRecipe
  id: WeaponDisablerPractice
  icon:
    sprite: Objects/Weapons/Guns/Battery/practice_disabler.rsi
    state: base
  result: WeaponDisablerPractice
  completetime: 15
  materials:
    Glass: 250
    Steel: 250

- type: latheRecipe
  id: MagazineBoxPistol
  result: MagazineBoxPistol
  completetime: 5
  materials:
    Steel: 650

- type: latheRecipe
  id: MagazineBoxPistolUranium
  result: MagazineBoxPistolUranium
  completetime: 25
  materials:
    Steel: 650
    Uranium: 60

- type: latheRecipe
  id: MagazineBoxPistolRubber
  result: MagazineBoxPistolRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300

- type: latheRecipe
  id: MagazineBoxMagnum
  result: MagazineBoxMagnum
  completetime: 5
  materials:
    Steel: 1250

- type: latheRecipe
  id: MagazineBoxMagnumRubber
  result: MagazineBoxMagnumRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300

- type: latheRecipe
  id: MagazineBoxRifle
  result: MagazineBoxRifle
  completetime: 5
  materials:
    Steel: 950

- type: latheRecipe
  id: MagazineBoxRifleRubber
  result: MagazineBoxRifleRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600

- type: latheRecipe
  id: MagazineBoxLightRifle
  result: MagazineBoxLightRifle
  completetime: 5
  materials:
    Steel: 1800

- type: latheRecipe
  id: MagazineBoxLightRifleRubber
  result: MagazineBoxLightRifleRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600

- type: latheRecipe
  id: CartridgePistolHighVelocity
  result: CartridgePistolHighVelocity
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeMagnumHighVelocity
  result: CartridgeMagnumHighVelocity
  completetime: 2
  materials:
    Steel: 40

- type: latheRecipe
  id: CartridgeLightRifleHighVelocity
  result: CartridgeLightRifleHighVelocity
  completetime: 2
  materials:
    Steel: 40

- type: latheRecipe
  id: CartridgeRifleHighVelocity
  result: CartridgeRifleHighVelocity
  completetime: 2
  materials:
    Steel: 30

- type: latheRecipe
  id: MagazineBoxPistolHighVelocity
  result: MagazineBoxPistolHighVelocity
  completetime: 5
  materials:
    Steel: 1250

- type: latheRecipe
  id: MagazineBoxMagnumHighVelocity
  result: MagazineBoxMagnumHighVelocity
  completetime: 5
  materials:
    Steel: 2450

- type: latheRecipe
  id: MagazineBoxLightRifleHighVelocity
  result: MagazineBoxLightRifleHighVelocity
  completetime: 5
  materials:
    Steel: 2050

- type: latheRecipe
  id: MagazineBoxRifleHighVelocity
  result: MagazineBoxRifleHighVelocity
  completetime: 5
  materials:
    Steel: 1850

- type: latheRecipe
  id: ShellShotgunIncendiary
  result: ShellShotgunIncendiary
  completetime: 2
  materials:
    Plastic: 20

- type: latheRecipe
  id: CartridgePistolIncendiary
  result: CartridgePistolIncendiary
  completetime: 2
  materials:
    Plastic: 10

- type: latheRecipe
  id: CartridgeMagnumIncendiary
  result: CartridgeMagnumIncendiary
  completetime: 2
  materials:
    Plastic: 20

- type: latheRecipe
  id: CartridgeLightRifleIncendiary
  result: CartridgeLightRifleIncendiary
  completetime: 2
  materials:
    Plastic: 20

- type: latheRecipe
  id: CartridgeRifleIncendiary
  result: CartridgeRifleIncendiary
  completetime: 2
  materials:
    Plastic: 15

- type: latheRecipe
  id: MagazineBoxPistolIncendiary
  result: MagazineBoxPistolIncendiary
  completetime: 5
  materials:
    Plastic: 650

- type: latheRecipe
  id: MagazineBoxMagnumIncendiary
  result: MagazineBoxMagnumIncendiary
  completetime: 5
  materials:
    Plastic: 1250

- type: latheRecipe
  id: MagazineBoxLightRifleIncendiary
  result: MagazineBoxLightRifleIncendiary
  completetime: 5
  materials:
    Plastic: 1800

- type: latheRecipe
  id: MagazineBoxRifleIncendiary
  result: MagazineBoxRifleIncendiary
  completetime: 5
  materials:
    Plastic: 950
