- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  minBankBalance: 350
  maxBankBalance: 550
  wageDepartment: Civilian
  wage: 40

- type: startingGear
  id: ReporterGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
