- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 72000
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatQMsoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackQuartermasterFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    pocket1: AppraisalTool
  innerclothingskirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelQuartermasterFilled
  duffelbag: ClothingBackpackDuffelQuartermasterFilled
