- type: department
  id: Legal
  name: department-Legal
  description: department-Legal-description
  color: "#F2B141"
  roles:
  - Magistrate
  - IAA
  - Lawyer
  accountNumber: 1323

- type: department
  id: Syndicate
  name: department-Syndicate
  description: department-Syndicate-description
  color: "#FF0000"
  roles:
  - SyndicateCaptain
  - SyndicateFirstMate
  - SyndicateEngineer
  - SyndicateDoctor
  - SyndicatePilot
  accountNumber: 9999

- type: department
  id: Freelance
  name: department-Freelance
  description: department-Freelance-description
  color: "#FFCF40"
  roles:
  - Freelancer
  accountNumber: 9998