################################################################################
##### General ##################################################################

[net]
port = 1214
bindto = "0.0.0.0"
log_late_msg = false

[database]
engine = "sqlite"
sqlite_dbpath = "build.sqlite"

[game]
desc = "VoidSector Build"
hostname = "Пустотная Стройка"
soft_max_players = 60
lobbyenabled = false
fallbackpreset = "Sandbox"
map = "Empty"
role_timers = false

[hub]
advertise = false

[server]
rules_file = "BuildRuleset"

[console]
login_host_user = "Makot"

[admin]
see_own_notes = true
note_fresh_days = 0
message_wait_time = 1
afk_time = 0.0

[physics]
grid_splitting = false

[procgen]
preload = false

[shuttle]
grid_fill = false
auto_call_time = 0
emergency = false
arrivals = false
preload_grids = false

################################################################################
##### In Game ##################################################################

[atmos]
space_wind = false

[biomass]
easy_mode = false

[vote]
timermap = 30

[shuttle]
grid_fill = false
arrivals = false
emergency = false
auto_call_time = 0

[rules]
time = 0.0

[tips]
enabled = false

[ooc]
enable_during_round = true

################################################################################
##### Discord ##################################################################

[discord]
rich_main_icon_id = "voidsector"
