- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobIAA

- type: playTimeTracker
  id: JobMagistrate

- type: playTimeTracker
  id: JobBlueShieldOfficer

- type: playTimeTracker
  id: JobSyndicateCaptain

- type: playTimeTracker
  id: JobSyndicateFirstMate

- type: playTimeTracker
  id: JobSyndicateEngineer

- type: playTimeTracker
  id: JobSyndicateDoctor

- type: playTimeTracker
  id: JobSyndicatePilot